name: PPTX
on:
  # push on master branch: build pptx (pandoc)
  push:
    branches: [master]
  # manually triggered: build pptx (pandoc)
  workflow_dispatch:


jobs:
  # build pptx format (pandoc): "make pptx"
  pptx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cagix/pandoc-lecture@master
      - run: make pptx

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: _pptx
          publish_dir: docs/
          force_orphan: true
